spring.application.name=ISUSA
server.port=${SERVER_PORT:8081}


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/isusa_main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
# ?? ????? ????? ??????? ? ????? (?????????? ???????? ? ????????/?????? ????????)
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
# ??????? ???????? ??? ?????????? ????? TEXT
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ????????? SQL-??????? ? ???????
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===  SECURITY (JWT) ===
# ????????? ???? ??? ??????? JWT-??????? (JwtService ???? ?????)
application.security.jwt.secret-key=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIGtleSBmb3IgSldUIGNvbXBpbGVkIGJ5IE1hemluZw==
# ????? ??????: 86400000 ?????????? = 24 ???
application.security.jwt.expiration=86400000
# ???? ?? ????????????? ??? ?????????? ????????? (AuthService ?? ?????)
isusa.default-student-role-name=STUDENT