# === ??????? ???????????? ===
spring.application.name=ISUSA
server.port=${SERVER_PORT:8081}

# === DATABASE ===
# ???????: ??? ????????? ???????? ???????????????? localhost:5433
# (???? ?????????? ? Docker Compose, SPRING_DATASOURCE_URL ???????? 'localhost' ?? 'db')
# === ??????? ?? ===
spring.datasource.jdbc-url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/isusa_main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# === ?? ?????? ===
reports.datasource.jdbc-url=${REPORTS_DATASOURCE_URL:jdbc:postgresql://localhost:5434/isusa_reports}
reports.datasource.username=${REPORTS_DATASOURCE_USERNAME:postgres}
reports.datasource.password=${REPORTS_DATASOURCE_PASSWORD:postgres}

# === ???????????? HIBERNATE (JPA) ===
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ????? ???????????? ????? ????? ???? ????? (create-drop)
spring.jpa.hibernate.ddl-auto=create-drop

# --- ??? ???????: ?????????? ????????????? ---
# ?? ???????? ?????????? data.sql ????? ????????? ???????
# ? ???????? Hibernate ????????? data.sql ????? ????????? ???????.
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.platform=
# ---------------------------------------------

spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG

# === SECURITY (JWT) ===
application.security.jwt.secret-key=VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIGtleSBmb3IgSldUIGNvbXBpbGVkIGJ5IE1hemluZw==
application.security.jwt.expiration=86400000
isusa.default-student-role-name=STUDENT

# === BRUTE-FORCE PROTECTION ===
isusa.security.max-failed-attempts=5
isusa.security.lock-duration-minutes=15

# === RSA ????? ??? KeyService ===
# ????????? ???? (X.509)
isusa.security.keys.public-base64=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7Ues0RAmYox7Mvv/1H86M/p9eN8gi+k/l+/UGn2wiL/GqDqtsfgzz8AJVmP5eRGzGOoV/as0jaUvh1LIdDMDh48RrileWeA3GaKGFCcEu9aawL0Ldc1/+713Qw6dfn5v3uLCpiiynXO4q60MyYiDgsiWqGwPei9QjunCxQ2F/TL9cfkKwctnOyXa0CtyT1y1YYs7ydtpWdQUwzSkKpx3imN50Vpgl58JEedbHgIYS+K/htGzCPVbpgbNIUG7R9BpxKXHkAxkU7V6pxndHYta7XX9V6rh90bU51KNpfioE9KCogpE9T7+TELXWKF1MWb1cJ2qb/Vr7rXeA/yJ/br7GQIDAQAB
# ????????? ???? (PKCS#8)
isusa.security.keys.private-base64=MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDtR6zRECZijHsy+//Ufzoz+n143yCL6T+X79QafbCIv8aoOq2x+DPPwAlWY/l5EbMY6hX9qzSNpS+HUsh0MwOHjxGuKV5Z4DcZooYUJwS71prAvQt1zX/7vXdDDp1+fm/e4sKmKLKdc7irrQzJiIOCyJaobA96L1CO6cLFDYX9Mv1x+QrBy2c7JdrQK3JPXLVhizvJ22lZ1BTDNKQqnHeKY3nRWmCXnwkR51seAhhL4r+G0bMI9VumBs0hQbtH0GnEpceQDGRTtXqnGd0di1rtdf1XquH3RtTnUo2l+KgT0oKiCkT1Pv5MQtdYoXUxZvVwnapv9Wvutd4D/In9uvsZAgMBAAECggEAENvtXwNfPtRNcp9uG3qYt5W+MYblCJvfjVuYffNdRjIeGtjke4cvozy5TR6YXK5Rw9zqCBaQitnoSRysKnlvcEPNlUrSLd+c+qDOFwN4tiH25+fmtw2NYOUi4qxYq2Kvby48d1Lf8gkFX4lRpcYh1fqLndbjuKJA/o6EbLzbvtQsINFnqIkS54rryF0t9jjP0oE8Kq+AUdNf6Ij9QQlXihr92/F77+Uw9o/9MIDxi1ovDYwsJrUP4nx4ck+mZc1eJqnQznGVh1S7kvTE1nknw9uewvnHdumFW6BYEyZaJC8uxFwL/AiZSoOZ6eD7WZx9YG8IZbw1u22EapGjIZfkmwKBgQD2GY6zBet50WlzCsz176aCs+smjbMcxwJHcBZxui0u5LB8T/Hw7pYZUy8iNLzvH5s32xJqYvH0YLChkT3NLWqo9eLEIhsvZxKn/QH1eWUTJxDRx3lxN76Ucckq7dMsmMa9u2FdhgDRnk+NKKK0yTopq4nW05dJV+jR5clOMyPWdwKBgQD200l3wt8bJb02TbbCxviGchUJcmIGS4gCmi5mOd1l+vd3SG7Y+abIczYiEZaiTF+Wa2JjrR7/K14zU4kSnEQODGuTA9C3htT3ki/i2EumzUYL8j4BhPSDk+2D199CxRwLhDvdq/XVpRPXESGfMh0u5b0cHFIRyTqD01GR317O7wKBgQCmTLLvKqrq0KXPRZcnAeClJetbTBmi8qAJoiaoh0SNEaBpAKTfSHpJdrq9BKI/fD4pSnJxTZduqf/xzfHTOkN/FVk9bEaui5pBxmiSdovkm1t0RrU72o2ARjvINJmk40A5aevrhOf8vlvHaZQ5UllpWy9z6durhiof3IVhwJERFQKBgQC0l81GWgfBpjA13lCdXNWUET6BJfbA4lzGgqb2Vto99o0/8nhgOvGj8mAmNzY+06CQv0tC4PUwADwxU6qUOk+087N14rHAxl9mMMjmshlQFxtsPDbQB8abyw1ajQUmpm+poXvn6hy5z8mfb0JpZ1Jg8OkX+0S1DMXKlEA3efa1cwKBgQDXGJEH97Lk2zCvxMOoaX62OEF6I0MBQesRGXnTyXJXQvZLgNeghAvdX2khoQourIDFCoEm1yz49YOqb1u+Pn1tzr8VjBfcxSGmqToBoGkxA1226ixMNq9A5wf9ycqKtFdaIYKGYoH0Cg0y7zqZsrg8JKCZ2I7+8AyczKmeQ3UkdQ==

# === EMAIL CONFIGURATION ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=isusa.sender@gmail.com
spring.mail.password=dqfm uwoi oias ziix
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

isusa.mail.from=isusa.sender@gmail.com